apiVersion: v1
kind: Pod
metadata:
  name: pv-debug
  namespace: cadvisor
spec:
  containers:
  - name: debug
    image: busybox
    command: ['sleep', '3600']
    volumeMounts:
    - name: cadvisor-storage
      mountPath: /data
  volumes:
  - name: cadvisor-storage
    persistentVolumeClaim:
      claimName: cadvisor-pvc