apiVersion: apps/v1
kind: Deployment
metadata:
  name: criu-coordinator-server
  namespace: monitor  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: criu-coordinator-server
  template:
    metadata:
      labels:
        app: criu-coordinator-server
    spec:
      containers:
      - name: coordinator-server
        image: salamander1223/criu-coordinator-server:latest
        securityContext:
          privileged: true
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: server-images
          mountPath: /tmp/server-images
      volumes:
      - name: server-images
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: coordinator-service
  namespace: monitor
spec:
  selector:
    app: criu-coordinator-server
  ports:
  - port: 8000
    targetPort: 8000