apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: controller-account
  name: controller-account
  namespace: monitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-account-role
rules:
- apiGroups: [""]  # Core API group
  resources: ["pods", "namespaces"]
  verbs: ["get", "list", "describe", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
  verbs: ["get", "list", "describe", "create", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "describe", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-account-binding
subjects:
- kind: ServiceAccount
  name: controller-account
  namespace: monitor
roleRef:
  kind: ClusterRole
  name: controller-account-role
  apiGroup: rbac.authorization.k8s.io