apiVersion: v1
kind: PersistentVolume
metadata:
  name: cadvisor-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/cadvisor
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cadvisor-pvc
  namespace: cadvisor
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi