apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: monitor
  labels: 
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values:
                - kind-worker
      serviceAccountName: controller-account
      containers:
      - name: postgres-container
        image: postgres:15
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: POSTGRES_USER
          value: "sfarokhi"
        - name: POSTGRES_PASSWORD
          value: "wordpass"
        - name: POSTGRES_DB
          value: "sfarokhi"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
      - name: metadata-container
        image: salamander1223/python-metadata:latest
        imagePullPolicy: IfNotPresent
        command: ["python3", "metadata.py"]
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 100m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 500Mi
        ports:
        - name: http
          containerPort: 8008
          protocol: TCP
        env:
        - name: SERVER_PORT
          value: "8008"
        - name: STORAGE_PATH
          value: "/storage"
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "sfarokhi"
        - name: DB_USER
          value: "sfarokhi"
        - name: DB_PASSWORD
          value: "wordpass"
        - name: SCHEDULER_TIME
          valueFrom:
            configMapKeyRef:
              name: scheduler-config
              key: scheduler-time
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        emptyDir: {}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-upload
  namespace: monitor
  labels:
    app: db-upload
spec:
  template:
    metadata:
      labels:
        app: db-upload
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-db
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z db-service 5432; do echo waiting for db-service; sleep 2; done;']
      containers:
      - name: db-upload-container
        image: salamander1223/python-db-upload:latest
        command: ["python", "upload_data.py", "test_data", "table"]
        args:
        - --host=db-service
        - --port=5432
        - --dbname=sfarokhi
        - --user=sfarokhi
        - --password=wordpass
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: monitor
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-service
  namespace: monitor
spec:
  selector:
    app: postgres
  ports:
  - name: http
    port: 8008
    targetPort: 8008
    protocol: TCP