apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: monitor
  labels: 
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres-container
        image: bitnami/postgresql:latest
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: POSTGRES_USER
          value: "sfarokhi"
        - name: POSTGRES_PASSWORD
          value: "wordpass"
        - name: POSTGRES_DB
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: monitor
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 32345