apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: foo
  labels:
    name: test-pod
  annotations:
    REGION: "CAL"
    EXPECTED_DURATION: "48"
spec:
  # For the control-plane migration
  tolerations:
  - operator: Equal
    effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  containers:
  - name: test-container
    image: busybox:latest
    command: ["sh", "-c", "echo Hello Kubernetes! && sleep 6000"]
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "128Mi"
        cpu: "1000m"
      limits:
        memory: "256Mi"
        cpu: "2000m"
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
