apiVersion: v1
kind: Pod
metadata:
  name: cpp-test-pod
  namespace: test-namespace
spec:
  nodeSelector:
    kubernetes.io/hostname: kind-worker
  containers:
    - name: cpp-container
      image: cpp-test:local
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: script-data
          mountPath: /script-data
  volumes:
    - name: script-data
      emptyDir: {}
  restartPolicy: Always
