FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY controller/main_req.txt main_req.txt
RUN pip install --no-cache-dir -r main_req.txt

# Copy script into the container
COPY controller/main.py /app/

# Set the entrypoint to run the script
CMD ["python3", "main.py"]
# 